management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  logback:
    rollingpolicy:
      max-history: 7
spring:
  main:
    banner-mode: "off"
  jackson:
    serialization:
      indent_output: true
