server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Configuração global de CORS para permitir a comunicação com o front-end.
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:5500"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allow-credentials: true

      # Rotas explícitas, usando os nomes exatos registados no Eureka (MINÚSCULAS).
      routes:
        - id: administrativo-service
          # A URI aponta para o nome exato do serviço no Eureka.
          uri: lb://clinica-medica-administrativo
          predicates:
            - Path=/administrativo/**
          filters:
            # Remove o prefixo '/administrativo' para que a requisição chegue correta ao microsserviço.
            - StripPrefix=1

        - id: agendamento-service
          uri: lb://clinica-medica-agendamento
          predicates:
            - Path=/agendamento/**
          filters:
            - StripPrefix=1

        - id: atendimento-service
          uri: lb://clinica-medica-atendimento
          predicates:
            - Path=/atendimento/**
          filters:
            - StripPrefix=1