global:
  scrape_interval: 15s # A cada 15 segundos, o Prometheus vai buscar as métricas.

scrape_configs:
  # Bloco de configuração para os seus micro-serviços Spring Boot
  - job_name: 'spring-micrometer'
    metrics_path: '/actuator/prometheus' # O endpoint que o Actuator expõe
    static_configs:
      - targets:
          # IMPORTANTE: Use 'host.docker.internal' para se referir à sua máquina local de dentro do contêiner
          - 'host.docker.internal:8088' # api-gateway
          - 'host.docker.internal:8080' # clinica-medica-administrativo
          - 'host.docker.internal:8081' # clinica-medica-agendamento
          - 'host.docker.internal:8083' # clinica-medica-atendimento