# Configurações do Banco de Dados para o perfil local
spring.datasource.url=jdbc:mysql://localhost:3306/clinicamedica?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do Hibernate para persistência de dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração de Segurança
application.security.jwt.secret-key=a2c8a7e6f0b3d5e8f1a3b5c7d9e0f2a4b6c8d0e2f1a3b5c7d9e0f2a4b6c8d0e2
application.security.jwt.expiration=3600000
application.security.jwt.refresh-token.expiration=86400000

# Define a porta exclusiva para este serviço
server.port=8083