# Porta em que o Eureka Server irá correr. 8761 é a porta padrão.
server.port=8761

# Nome da aplicação que aparecerá no dashboard do Eureka
spring.application.name=eureka-server

# Configurações específicas do Eureka Server
# Como este é o único servidor, dizemos a ele para não tentar registar-se noutro servidor.
eureka.client.register-with-eureka=false
# Também dizemos para não tentar obter o registo de outros servidores.
eureka.client.fetch-registry=false