# Define o nome do serviço para o Eureka
spring.application.name=clinica-medica-administrativo

# Define a porta padrão do serviço
server.port=8081

# Define o perfil ativo. Usaremos 'local' para carregar as configurações abaixo.
spring.profiles.active=local