

# Configure the database driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Sets the MySQL dialect for Hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
# SQL initialization settings
# Disables automatic schema generation
spring.jpa.hibernate.ddl-auto=update
# Path to the schema SQL file
spring.sql.init.schema-locations=classpath:db/schema.sql
# Path to the data SQL file
spring.sql.init.data-locations=classpath:db/data.sql

# URL base do Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#define o perfil ativo
spring.profiles.active=local

# ==================================
# CONFIGURAÇÕES DE SEGURANÇA E JWT
# ==================================
# ATENÇÃO: Esta chave é apenas um exemplo. Em produção, use um gerador online para criar uma chave Base64 segura e longa.
security.jwt.secret-key=4D6251655468576D5A7134743777217A25432A462D4A614E645267556B587032
# Tempo de expiração do token: 24 horas em milissegundos (24 * 60 * 60 * 1000)
security.jwt.expiration-time=86400000

# ==================================
# CONFIGURAÇÕES DO EUREKA CLIENT
# ==================================

# Define o nome que este serviço terá no dashboard do Eureka.
# É importante que seja único e descritivo.
spring.application.name=clinica-medica-administrativo

# Endereço do nosso Servidor Eureka.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ==================================
# CONFIGURAÇÕES DO SPRING ACTUATOR
# ==================================

# Expõe os endpoints 'health', 'info', e agora 'prometheus' via web.
management.endpoints.web.exposure.include=health,info,prometheus

